### ISSUE TITLE
proposal: support AAAA records

### ISSUE THREAD

**Issue by marcelo321** [jimen0/fdns#5]
Sorry, would it be possible to parse ipv6 too?

**Comment by jimen0** [comment]
Hi,

Thank you for the feature request. I'll try to find time this month to implement it as I agree on it being useful. Can't promise anything as I'm quite busy at the moment. Feel free to submit a PR if you really need it ASAP 😄 

Best,
Miguel

**Comment by jimen0** [comment]
Hi @marcelo321 and @0xatul

I just pushed the [v2.0.0](https://github.com/jimen0/fdns/releases/tag/v2.0.0) tag of the project which adds support for `AAAA` records and much more!

```console
$ git clone https://github.com/jimen0/fdns
$ cd fdns/cmd/fdns
$ go install
$ fdns \
    --domains yahoo.com,github.com \
    --records aaaa \
    --goroutines 4 \
    --url https://opendata.rapid7.com/sonar.fdns_v2/2020-07-24-1595549209-fdns_any.json.gz \
    --verbose
1056405.ostk.bm2.prod.ne1.yahoo.com
1070605.ostk.bm2.corp.bf1.yahoo.com
1072626.ostk.bm2.prod.gq1.yahoo.com
1087074.ostk.bm2.corp.ne1.yahoo.com
...
```

Let me know if that solves your problem, please!

Best,
Miguel
